version: "3"

services:
  db:
    container_name: wt-mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: dcms
      MYSQL_PASSWORD: ash
      MYSQL_DATABASE: dcms
    ports:
      - 3307:3306
    volumes:
      - ./config/db-dump:/docker-entrypoint-initdb.d
  myadmin:
    container_name: wt-myadmin
    depends_on:
      - db
    image: phpmyadmin
    links:
      - db:db
    ports:
      - 3607:80
