version: "3"

services:
  db:
    container_name: wt-mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: dcms
      MYSQL_PASSWORD: ash
      MYSQL_DATABASE: dcms
    ports:
      - 3307:3306
    volumes:
      - ./config/db-dump:/docker-entrypoint-initdb.d

  myadmin:
    container_name: wt-myadmin
    depends_on:
      - db
    image: phpmyadmin
    links:
      - db:db
    ports:
      - 3607:80

  server:
    image: php:8.0-apache
    ports:
      - "81:80"
    volumes:
      - ./config/apache2.conf:/etc/apache2/apache2.conf
      - ./:/var/www/html
    container_name: php-apache